### ISSUE TITLE
The results view is cropped

### ISSUE THREAD

**Issue by geoffreytools** [wallabyjs/atom-quokka#11] opened 2020-08-08 17:22 UTC
The results view is taller than the visible area. When its content overflows, the scrollbar is off or does not appear at all

The following fixed it for me

```less
// quokka.less
.quokka-results-view {
  // max-height: 600px;
  height: 100%;
```

**Comment by ArtemGovorov** [comment] 2020-08-10 01:18
Thanks for the report. The issue is fixed in the latest published plugin version.

**Closed as completed by ArtemGovorov** 2020-08-10 01:18 UTC
