### ISSUE TITLE
Uncaught TypeError: Cannot read property 'visible' of undefined

### ISSUE THREAD

**Issue by monzoor** [wallabyjs/atom-quokka#9] opened 2018-05-04 21:12 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [atom-quokka](https://github.com/wallabyjs/atom-quokka) package 1.0.71

### Stack Trace

Uncaught TypeError: Cannot read property 'visible' of undefined

```
At /Users/monzoor/.atom/packages/atom-quokka/node_modules/quokka-atom/build/quokka.js:1

TypeError: Cannot read property 'visible' of undefined
    at Function._sessionIsActive (/packages/atom-quokka/node_modules/quokka-atom/build/quokka.js:1:24323)
    at /packages/atom-quokka/node_modules/quokka-atom/build/quokka.js:1:17357)
    at emitOne (events.js:96:13)
    at c.emit (events.js:191:7)
    at c._stats (/packages/atom-quokka/node_modules/quokka-atom/build/extension/dist/wallaby/client.js:14:5224)
    at /packages/atom-quokka/node_modules/quokka-atom/build/extension/dist/wallaby/client.js:14:2833)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:194:7)
    at Receiver.ontext (/packages/atom-quokka/node_modules/quokka-atom/build/extension/dist/wallaby/node_modules/ws/lib/WebSocket.js:841:10)
    at /packages/atom-quokka/node_modules/quokka-atom/build/extension/dist/wallaby/node_modules/ws/lib/Receiver.js:536:18
    at /packages/atom-quokka/node_modules/quokka-atom/build/extension/dist/wallaby/node_modules/ws/lib/Receiver.js:368:7
    at /packages/atom-quokka/node_modules/quokka-atom/build/extension/dist/wallaby/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:383:3)
    at onwrite (_stream_writable.js:374:7)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:625:5)
```

### Commands

```
     -3:42 intentions:highlight (input.hidden-input)
     -1:32.4.0 platformio-ide-terminal:paste (textarea.)
     -1:25.6.0 core:paste (input.hidden-input)
     -1:21.2.0 core:save (input.hidden-input)
     -1:04.7.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
 18x -1:01.6.0 core:move-down (input.hidden-input)
  2x -0:57.9.0 core:move-up (input.hidden-input)
     -0:56.6.0 core:backspace (input.hidden-input)
 14x -0:55.7.0 core:move-up (input.hidden-input)
     -0:48.1.0 core:confirm (input.hidden-input)
     -0:48.1.0 quokka:create-typescript-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:47.1.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.2.0 
atom-quokka 1.0.71 
atom-ternjs 0.18.3 
autocomplete-modules 2.0.0 
autocomplete-paths 2.12.2 
blade-snippets 0.2.0 
busy-signal 1.4.3 
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.19 
goto-definition 1.3.4 
Hydrogen 2.4.1 
hyperclick 0.1.5 
intentions 1.1.5 
javascript-snippets 1.2.1 
js-hyperclick 1.13.0 
js-refactor 0.8.1 
jslint 1.5.1 
linter 2.2.0 
linter-ui-default 1.7.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
react 0.18.0 
todo-show 2.3.0 
```

**Comment by ArtemGovorov** [comment] 2018-05-05 00:55
Thanks for the report. The issue is fixed in v1.0.72.

**Closed as completed** 2018-05-05 00:54 UTC
